### ISSUE TITLE
any demo results?

### ISSUE THREAD

**Issue by hj0921** [epeake/ModifiedKneserNey#2]
Hi epeake,

My results are not reasonable to me... May I ask for uploading any demo results? Thank you!
such as a training set you use and some test results. Thanks a lot!

Best wishes!

**Comment by epeake** [comment]
Hi hj0921!  Sorry I just saw this.  I will come up with some demo results this coming week if you are still interested!

**Comment by epeake** [comment]
Also, if you have your specific example that you would like me to look at (for example, where your results are not reasonable), let me know.

**Comment by epeake** [comment]
I am unfortunately too busy with other projects to update this repository.  Feel free to fork if you wish to improve upon it!
